author: Eagle # 作者
description: Eagle's blog
keyword: hexo-theme, vuejs
favicon: /css/images/favicon.ico

excerpt_link: Read more

menu:
 Home: /
 Tags: /tags/
 Archives: /archives/
#  Projects: /project/
 About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: false

# qrcode
qrcode: false

# comment
# you can set gitment or uyan

# comment: gitment

# gitment config
gitment_owner: Eagle
gitment_repo: eagleLiying.github.io
# gitment_oauth_id: 0f87e490e00ee3fd87ef
# gitment_oauth_secret: 4a9d2b148e7971c2201ad12131ce8bf8159ccd2e

# uyan
# if you want to use uyan as your blog comment, plz remove/comment out gitment config

baidu_id: 

about: 
  banner: http://file.muyutech.com/about.jpg
  avatar: /css/images/avater.png
  description: "喜欢自己折腾一些感兴趣的小东西"
  # weibo_username: Eagle
  # twitter_username: Eagle
  github_username: eagleLiying
  # zhihu_username: yummy1121
  # douban_username: eagle
  # linkedin_username:

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML
