author: Eagle # 作者
description: Eagle's blog
keyword: hexo-theme, vuejs
favicon: /css/images/favicon.ico

excerpt_link: Read more

menu:
 Home: /
 Tags: /tags/
 Archives: /archives/
#  Projects: /project/
 About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: false

# qrcode
qrcode: false

# comment
# you can set gitment or uyan

# 注释所有畅言配置
# 注释所有gitalk配置
# livere配置
livere: 
  enable: true
  uid: MTAyMC80MDAwNy8xNjUzNA==

# comment: gitment

# # gitment config
# gitment_owner: eagleLiying
# gitment_repo: https://eagleliying.github.io
# gitment_oauth_id: b1af9beae5ee2358245a
# gitment_oauth_secret: 9dca8ab92adf13f3d553cefa7bd61df1c016fac7

# uyan
# if you want to use uyan as your blog comment, plz remove/comment out gitment config

# baidu_id: 
baidu_tongji: true


about: 
  banner: http://file.muyutech.com/about.jpg
  avatar: /css/images/avater.png
  description: "喜欢自己折腾一些感兴趣的小东西"
  # weibo_username: Eagle
  # twitter_username: Eagle
  github_username: eagleLiying
  zhihu_username: yummy1121
  # douban_username: eagle
  # linkedin_username:

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML
